### ISSUE TITLE
Clarify README instructions

### ISSUE THREAD

**Issue by samajammin** [estrada9166/labeler#1]
Hi & thank you for creating this project!

Could you please clarify your README instructions?
> Create a config file in the root of your project

Does this mean create a yml file (e.g. `labeler-config.yml`) in the root of my `.github` directory?

**Comment by estrada9166** [comment]
Hi! thanks for creating this issue!

It means in the root of the whole project, something like
```
.
│
├── .github 
│   ├── workflows
│   │    ├── labeler.yml
│   │    └── ...
│   └── ...
├── package.json
├── labeler-config.yml
└── ...
```

**Comment by samajammin** [comment]
Ok, thanks! If that specific filename (labeler-config.yml) is necessary, I'd suggest adding that to the README.

Looking forward to testing this out!

**Comment by samajammin** [comment]
So must the workflow be named `labeler.yml`? I'm wondering if this will conflict with our existing workflow file: https://github.com/ethereum/ethereum-org-website/blob/dev/.github/labeler.yml

**Comment by estrada9166** [comment]
No! you can use another name... so, it can be something like this
```
.
│
├── .github 
│   ├── workflows
│   │    ├── labeler-action.yml
│   │    └── ...
│   └── ...
├── package.json
├── labeler-config.yml
└── ...
```
#### .github/workflows/labeler-action.yml
```yml
name: Labeler

on: [pull_request_review, pull_request_review_comment]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Labeler
      uses: estrada9166/labeler@v1-release
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CONFIG_PATH: labeler-config.yml 
```
#### labeler-config.yml
```yml
onComment:
  set:
    - WIP

onApproved:
  remove:
    - WIP
  set:
    - First review
    - Ready to merge

onChangesRequested:
  remove:
    - Ready to merge
    - Waiting 1st review
    - Waiting 2nd review
  set:
    - WIP 
```
