### ISSUE TITLE
GraphQL error when using this action

### ISSUE THREAD

**Issue by obrassard** [estrada9166/labeler#3]
Hi ! I was trying to setup this action as part of one of my projects, however I wasn't able to make it work properly. I couldn't figure why, every time the workflow runs I get this error: 

> GraphqlError: Variable $input of type RemoveLabelsFromLabelableInput! was provided invalid value for labelIds (Expected value to not be null)

Heres my workflow yaml file : 

```yml
name: Auto Label PR
on: [pull_request_review, pull_request_review_comment]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Label PRs
      uses: estrada9166/labeler@v1
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CONFIG_PATH: .github/labeler-config.yml
```

and the `labeler-config.yml` file : 

```yml
onComment:
  set:
    - Need review

onApproved:
  remove:
    - Need review
    - Work Needed
  set:
    - LGTM

onChangesRequested:
  remove:
    - Need review
  set:
    - Work Needed
```

Is there something I've missed in this configuration ?

**Comment by chapmandu** [comment]
The cause of this seem to be the omission of the `- remove` on the `onComment` event.

It can be worked around by doing this:

```
onComment:
  set:
    - comments added
  remove:
    - void # workaround
```
